import tools from './tools.js'

const profiles = [
  {
    id: 'merge', slug: 'how-to-merge-pdf-files', title: 'How to Merge PDF Files Into One Clean Document',
    description: 'Learn how to combine PDF files in the right order, avoid duplicate pages, review transitions, and prepare one clear document for sharing.',
    situation: 'Merging works best when the source files belong in one packet and the reader benefits from a single order. A report with appendices, a set of signed forms, or several chapters are good examples. Unrelated records are usually easier to manage as separate files.',
    preparation: 'Open every source before combining anything. Note the page count, remove accidental blank scans, rotate sideways pages, and give the working copies numbered filenames. Numbered names make the intended order obvious when several files have similar titles.',
    decisions: 'Choose the order from the reader\'s point of view. Put a cover or explanation first, keep multi-page forms together, and place evidence after the section it supports. Decide whether existing page numbers still make sense before adding a new set to the packet.',
    mistakes: ['Adding files without checking their page counts can hide a missing second page.', 'Two documents may each include the same cover or instructions, which creates an untidy packet.', 'Judging only from thumbnails can miss sideways text, clipped scans, and a source inserted in the wrong place.'],
    related: ['reorder', 'page-numbers', 'compress'],
  },
  {
    id: 'split', slug: 'how-to-split-a-pdf-by-page-range', title: 'How to Split a PDF by Page Range',
    description: 'Extract the pages you need from a PDF while keeping sections complete, filenames clear, and private material out of the shared copy.',
    situation: 'Splitting is useful when a long PDF contains one chapter, one form, or a small set of pages that should be shared separately. It can also create manageable sections from a scan that is too large for email or an upload portal.',
    preparation: 'Read the receiving instructions and write down the exact page range. Compare the printed page numbers with the PDF reader\'s page counter because a cover and contents page can make them different. Keep the full source as the reference copy.',
    decisions: 'Keep related pages together. A signature page, table continuation, or back side of a form may look separate in a thumbnail but still belong to the previous page. Choose filenames that describe each extracted section without revealing private information.',
    mistakes: ['Using printed page numbers without checking the reader counter can select the wrong range.', 'Removing a continuation page can make a table or form incomplete.', 'Sending the full document when only two pages are needed exposes information for no useful reason.'],
    related: ['merge', 'redact', 'compress'],
  },
  {
    id: 'reorder', slug: 'how-to-reorder-pdf-pages', title: 'How to Reorder PDF Pages Without Losing Track',
    description: 'Put PDF pages in a clear sequence, repair scanner order, keep sections together, and verify every moved page before sharing.',
    situation: 'Page reordering fixes scans saved back to front, cover sheets placed in the middle, and appendices that arrived before the main report. The goal is a reading path that makes sense without changing the content on each page.',
    preparation: 'Save a working copy and write a short outline of the desired order. Record the current page count and identify groups that must stay together. Large thumbnail grids are easier to manage when you move one section at a time.',
    decisions: 'Decide whether a landscape page is intentionally wide or simply sideways. Keep both sides of a scanned sheet together. If existing page numbers conflict with the new sequence, remove or explain them before placing continuous packet numbers.',
    mistakes: ['Moving many similar thumbnails at once makes it hard to notice one page dropped in the wrong section.', 'Separating a signature from its agreement can make the packet confusing.', 'Adding page numbers before the order is final can leave the visible sequence wrong.'],
    related: ['rotate', 'page-numbers', 'merge'],
  },
  {
    id: 'compress', slug: 'how-to-compress-a-pdf', title: 'How to Compress a PDF and Keep It Readable',
    description: 'Reduce PDF file size while protecting small text, signatures, charts, scans, and the details a recipient actually needs.',
    situation: 'Compression is helpful for email limits, application portals, storage, and slow connections. The useful target is not the smallest possible file. It is a file that fits the requirement while every necessary detail remains readable.',
    preparation: 'Keep the original and inspect what makes it large. A short scan can be bigger than a long text report because every page is an image. Remove duplicate or unneeded pages before lowering the quality of the material that remains.',
    decisions: 'Match quality to the final use. A phone-readable copy can be smaller than a professional print file. Preserve color when it carries meaning, and inspect footnotes, account numbers, barcodes, signatures, and thin chart lines after compression.',
    mistakes: ['Choosing maximum compression first can make small numbers impossible to trust.', 'Converting meaningful color pages to grayscale can remove chart or annotation information.', 'Compressing the same output repeatedly lowers quality without fixing the source of the size.'],
    related: ['split', 'pdf-to-image', 'merge'],
  },
  {
    id: 'rotate', slug: 'how-to-rotate-pdf-pages', title: 'How to Rotate PDF Pages the Right Way',
    description: 'Correct sideways and upside-down PDF pages, handle mixed orientations, and check that the exported rotation works in another reader.',
    situation: 'Rotation is common after phone scanning, copier mistakes, and packets that mix portrait forms with landscape charts. Some landscape pages are already correct, so the job is to fix the pages that are hard to read rather than force one orientation on everything.',
    preparation: 'Move through the full PDF and list the pages that need correction. Check whether page labels match the reader counter. Save a working copy because applying one rotation to the whole file can create new problems in a mixed document.',
    decisions: 'Rotate selected pages when only part of the document is wrong. Leave a landscape table wide when that is how it was designed. After export, make sure the visible content, crop boundary, text selection, and printing orientation all agree.',
    mistakes: ['Applying rotation to every page can turn correct landscape pages sideways.', 'Judging one preview page can miss other scanner errors later in the file.', 'Confusing rotation with cropping can leave large borders or cut content that needs a separate fix.'],
    related: ['crop', 'reorder', 'pdf-to-text'],
  },
  {
    id: 'page-numbers', slug: 'how-to-add-page-numbers-to-a-pdf', title: 'How to Add Page Numbers to a PDF',
    description: 'Add useful PDF page numbers after the order is final, choose a readable position, and avoid covering existing footers or signatures.',
    situation: 'Page numbers help with reports, meeting packets, class submissions, and anything that will be printed or discussed by page. They are most useful when one continuous number identifies every page in the finished packet.',
    preparation: 'Finish merging, splitting, rotating, and reordering before numbering. Look at existing headers and footers on several pages. Choose a position with enough empty space, then decide whether the cover should be counted, displayed, or left unnumbered.',
    decisions: 'Use a starting number that matches the document\'s role. An appendix may continue an earlier packet, while a new report normally starts at one. Keep the text readable but quiet, and explain the difference if original documents already show their own internal numbers.',
    mistakes: ['Numbering before the page order is final creates a sequence that no longer matches.', 'Placing numbers over a footer, stamp, or signature can damage important content.', 'Using very small or pale numbers makes them useless in print and at normal zoom.'],
    related: ['reorder', 'merge', 'watermark'],
  },
  {
    id: 'word-to-pdf', slug: 'how-to-convert-word-to-pdf', title: 'How to Convert Word to PDF Without Layout Surprises',
    description: 'Prepare a DOCX file for PDF conversion, check fonts and page breaks, and review the downloaded document before submitting it.',
    situation: 'Converting Word documents is useful for resumes, assignments, letters, reports, and files that should look consistent when opened by someone else. A PDF freezes the visual layout, but it is not a replacement for the editable DOCX source.',
    preparation: 'Finish track changes, comments, headings, page breaks, and margins in the source. Use fonts that are available or embedded, update the table of contents, and check image placement. Keep the DOCX because later content changes are easier there.',
    decisions: 'Choose the intended paper size and inspect sections with tables, columns, equations, and floating images. Check links and accessibility structure after conversion. A clean preview is encouraging, but the downloaded PDF is the version that must be reviewed.',
    mistakes: ['Leaving comments or tracked changes visible can expose editing history.', 'Missing fonts can change line wrapping and push content onto another page.', 'Editing a converted PDF for major revisions is harder than correcting the Word source and exporting again.'],
    related: ['merge', 'compress', 'edit'],
  },
  {
    id: 'excel-to-pdf', slug: 'how-to-convert-excel-to-pdf', title: 'How to Convert Excel to PDF So Tables Stay Readable',
    description: 'Prepare spreadsheet print areas, page orientation, scaling, headers, and formulas before creating a PDF that other people can read.',
    situation: 'Spreadsheet conversion is useful for budgets, schedules, invoices, grade sheets, and reports that should be viewed without editing formulas. Wide tables need more preparation than ordinary text because a poor scale can make every cell too small.',
    preparation: 'Set the print area, choose portrait or landscape orientation, and review page breaks in the spreadsheet. Hide unused rows and columns, update formulas, and decide which sheet tabs belong in the output. Keep the workbook as the editable source.',
    decisions: 'Scale a table only as much as readability allows. Repeat header rows when a table spans pages, and include units, dates, and labels a reader needs. Check whether formulas display results correctly and whether hidden information should remain excluded.',
    mistakes: ['Forcing a very wide sheet onto one page can create unreadable text.', 'An undefined print area can export hundreds of empty cells.', 'Sharing the PDF without checking totals can preserve an outdated formula result.'],
    related: ['crop', 'merge', 'watermark'],
  },
  {
    id: 'image-to-pdf', slug: 'how-to-convert-images-to-pdf', title: 'How to Convert Images to One PDF',
    description: 'Turn photos and scans into an ordered PDF while keeping pages straight, readable, reasonably sized, and easy to share.',
    situation: 'Image conversion helps with receipt photos, handwritten notes, signed pages, artwork, and phone scans. The final PDF can keep several images in one order, but the source quality sets a limit on how clear the result can become.',
    preparation: 'Use the sharpest original images, remove accidental duplicates, and rotate photos before arranging them. Check that every corner of a document is visible and that shadows do not cover text. Rename or number images when their order matters.',
    decisions: 'Choose a page size and image fit that does not crop important edges. Preserve enough resolution for small handwriting or numbers. Decide whether photographs need color and whether ordinary black text scans can use a smaller grayscale output.',
    mistakes: ['A blurry photograph remains blurry after it is placed in a PDF.', 'Mixing camera orientations without review can create sideways pages.', 'Using full camera resolution for every simple receipt can make the final file unnecessarily large.'],
    related: ['rotate', 'crop', 'compress'],
  },
  {
    id: 'html-to-pdf', slug: 'how-to-convert-html-to-pdf', title: 'How to Convert HTML to PDF Reliably',
    description: 'Prepare HTML, styles, fonts, images, and page breaks for a PDF that keeps the intended content without unsafe or missing assets.',
    situation: 'HTML conversion works well for reports, receipts, templates, saved notes, and simple pages that need a fixed printable form. Web pages are designed for flexible screens, while PDF pages have fixed dimensions, so some layout choices need adjustment.',
    preparation: 'Use self-contained HTML when possible. Make sure styles, images, and fonts are available to the browser, remove scripts that are not needed for the document, and set a clear page width. Preview long tables and sections that could split across pages.',
    decisions: 'Choose print-friendly colors, margins, and font sizes. Decide which navigation, buttons, and interactive parts belong in a static document. External assets can fail because of permissions or network rules, so important images should be included in a reliable way.',
    mistakes: ['Screen-only navigation can waste space and confuse a printed document.', 'External images may disappear when the browser cannot access them.', 'A layout built only for a wide monitor can overflow a normal PDF page.'],
    related: ['edit', 'compress', 'merge'],
  },
  {
    id: 'pdf-to-image', slug: 'how-to-convert-pdf-pages-to-images', title: 'How to Convert PDF Pages to Images',
    description: 'Export PDF pages as useful images by choosing the right format, resolution, page range, filenames, and quality for the next task.',
    situation: 'Page images are useful for thumbnails, presentations, previews, social posts, and systems that do not accept PDFs. An image preserves the visual page but loses selectable text, links, form controls, and most document structure.',
    preparation: 'Decide which pages are needed and how the images will be used. Check the page at a useful zoom, crop unwanted margins if appropriate, and keep the original PDF. A whole report may create many output files, so plan a naming order.',
    decisions: 'Use PNG for sharp diagrams, interface screenshots, or text that needs crisp edges. JPG is often smaller for photographs. Choose enough resolution for the destination without generating huge images that a website or presentation will resize anyway.',
    mistakes: ['Exporting every page when only one figure is needed creates unnecessary files.', 'Low resolution can make small text unreadable when the image is enlarged.', 'Treating an image as an accessible replacement removes text search and screen-reader structure.'],
    related: ['crop', 'image-to-pdf', 'pdf-to-text'],
  },
  {
    id: 'pdf-to-word', slug: 'how-to-convert-pdf-to-word', title: 'How to Convert PDF to Word and Keep the Document Usable',
    published: '2026-07-24',
    description: 'Learn how PDF to Word conversion works, what stays editable, why layouts can change, and how to review a DOCX before using it for school or work.',
    situation: 'PDF to Word conversion is useful when the editable source is missing and the remaining PDF needs a correction, update, or reuse. It can help with reports, resumes, letters, manuals, assignments, and research material. It is less useful when the PDF is only a scan or when the original Word file is still available and can be edited directly.',
    preparation: 'Open the PDF in a normal reader and check whether the text can be selected. Record the page count and look for columns, tables, formulas, rotated labels, forms, links, scans, and unusual fonts. These details affect how much of the Word file can remain editable. Keep the PDF as a reference because the DOCX should be compared with it after conversion.',
    decisions: 'Decide whether editability or exact visual matching matters more for the next task. A Word document can use editable text boxes and images to follow the PDF page, but it may not behave like a document that was originally written in Word. For a large rewrite, rebuilding a clean flowing document may be better than forcing every fixed PDF coordinate into an editable layout.',
    mistakes: ['Assuming a converted DOCX is the original source can hide missing styles, paragraph structure, and revision history.', 'Opening the result in only one office program can miss font substitution or layout differences in the program the recipient uses.', 'Editing a complex converted page before comparing it with the PDF can make it harder to tell whether a problem came from conversion or a later change.'],
    review: [
      'Close the converter preview and open the downloaded DOCX in the office program you plan to use. Confirm the page count, paper size, orientation, columns, smallest text, images, tables, links, headers, footers, and any page with equations or unusual fonts. A file that opens successfully can still contain wrapping or substitution problems.',
      'Compare the DOCX with the source PDF page by page. Check whether selectable text remains editable, whether image-based fallback areas are clear, and whether a table still keeps the right rows and columns. Pay attention to the boundary between editable objects and visual artwork because those elements can overlap differently in another Word-compatible program.',
      'Save a separate edited copy before making major changes. If the recipient uses Microsoft Word, LibreOffice, or Google Docs, test the file in that environment because each program can interpret positioned DOCX objects differently. Keep the source PDF and the untouched converted DOCX until the revised document has been accepted.',
    ],
    related: ['word-to-pdf', 'pdf-to-text', 'edit'],
  },
  {
    id: 'pdf-to-text', slug: 'how-to-extract-text-from-a-pdf', title: 'How to Extract Text From a PDF',
    description: 'Copy useful PDF text while understanding scans, columns, reading order, OCR errors, and the layout that plain text cannot preserve.',
    situation: 'Text extraction helps with notes, quotations, search, research, and moving content into another draft. It works best when the PDF stores real characters. A scanned page may only contain an image and can require OCR before words become searchable.',
    preparation: 'Test whether individual words can be selected and search for a clear phrase. Check several pages because one file can mix digital text with scans. Keep page references beside extracted notes so important passages can be checked against the source.',
    decisions: 'Decide whether plain text is enough or the visual layout carries meaning. Columns, tables, footnotes, and equations may extract in a confusing order. Review names, dates, citations, totals, and symbols character by character when accuracy matters.',
    mistakes: ['Assuming an empty result means the page has no words ignores image-only scans.', 'Quoting extracted text without checking the page can preserve an OCR or reading-order error.', 'Expecting plain text to preserve table relationships can change the meaning of the data.'],
    related: ['wcag', 'edit', 'pdf-to-image'],
  },
  {
    id: 'edit', slug: 'how-to-edit-a-pdf', title: 'How to Edit a PDF Without Breaking Its Layout',
    description: 'Edit PDF text and objects carefully, understand embedded fonts and scans, and verify the downloaded file around every changed area.',
    situation: 'PDF editing is useful for small corrections, moved labels, added images, notes, shapes, and signatures. It is different from editing the Word or design file that created the PDF because page content may be split into many small objects.',
    preparation: 'Keep the original and identify whether the target text is selectable. Check the font, size, spacing, nearby lines, and page boundary before making a change. If the source document is available, use it for large revisions and export a fresh PDF.',
    decisions: 'Make the smallest change that solves the problem. Match existing typography when editing a form or report, and use a new text style only when the addition is meant to stand out. Review scans and uncommon symbols closely because they can use special encodings.',
    mistakes: ['Replacing a whole paragraph for one typo can disturb wrapping and spacing.', 'Using a substitute font without comparison can make edited text look obviously different.', 'Trusting only the canvas can miss a position or font problem in the exported PDF.'],
    related: ['redact', 'sign', 'compress'],
  },
  {
    id: 'watermark', slug: 'how-to-add-a-watermark-to-a-pdf', title: 'How to Add a Watermark to a PDF',
    description: 'Choose useful watermark text, placement, opacity, and page coverage without making the original document hard to read.',
    situation: 'Watermarks can label drafts, confidential copies, samples, approvals, and documents prepared for a specific recipient. A watermark is a communication aid, not a guarantee that copying or editing becomes impossible.',
    preparation: 'Decide what the label should communicate and which pages need it. Review pages with dark images, tables, signatures, and existing stamps. Keep the source because the clean version may still be required later.',
    decisions: 'Use short text, readable contrast, and enough transparency to keep the content usable. A diagonal center mark is noticeable, while a footer label can be less distracting. Check every page type because one setting may disappear over a dark photograph.',
    mistakes: ['A very dark watermark can make text and signatures difficult to read.', 'Putting a confidential label on only the cover may leave separated pages unmarked.', 'Treating a watermark as redaction leaves the underlying private information in the file.'],
    related: ['redact', 'encrypt', 'page-numbers'],
  },
  {
    id: 'redact', slug: 'how-to-redact-a-pdf', title: 'How to Redact a PDF Safely',
    description: 'Remove private PDF content instead of covering it, then test search, copy, extraction, images, metadata, and the exact shared copy.',
    situation: 'Redaction is needed when a shared document must not reveal names, addresses, account numbers, signatures, faces, or another protected detail. A shape placed over content can look correct while the original text remains recoverable.',
    preparation: 'Work on a copy and make a list of every item that must be removed. Search for variations, partial numbers, headers, comments, and metadata. Inspect scanned pages manually because their visible words may not appear in search.',
    decisions: 'Mark the full sensitive area with a small safety margin, apply the redactions, and export a new file. Decide whether sharing fewer pages is safer than redacting unrelated sections. Use a neutral filename when the original name reveals private information.',
    mistakes: ['Drawing a black rectangle usually covers content without removing it.', 'Checking only visible pages can miss the same value in comments, attachments, or metadata.', 'Sending the editing project instead of the applied export can expose the original content.'],
    related: ['pdf-to-text', 'split', 'encrypt'],
  },
  {
    id: 'crop', slug: 'how-to-crop-pdf-pages', title: 'How to Crop PDF Pages Without Cutting Content',
    description: 'Trim scanner borders and extra margins while protecting headers, page numbers, notes, printer space, and pages with different layouts.',
    situation: 'Cropping can remove scanner shadows, oversized white borders, and unwanted edge material. It changes the visible page area, so it should be used carefully when content sits close to a margin or pages have different sizes.',
    preparation: 'Inspect several pages at high zoom and keep the original. Look for page numbers, handwritten notes, crop marks, stamps, and content that appears only on later pages. Decide whether one crop fits all pages or selected pages need separate settings.',
    decisions: 'Leave a small comfortable margin instead of trimming directly against letters. Consider printing requirements and binding space. Cropping can improve the view, but it is not a secure way to remove private information that may remain outside the visible boundary.',
    mistakes: ['Applying the first page\'s crop to every page can cut a wider chart later in the file.', 'Removing all white space can make the result uncomfortable to read or print.', 'Using crop instead of redaction can leave hidden page objects recoverable.'],
    related: ['rotate', 'redact', 'compress'],
  },
  {
    id: 'encrypt', slug: 'how-to-password-protect-a-pdf', title: 'How to Password-Protect a PDF',
    description: 'Choose a strong PDF password, protect a new copy, test access, and share the password through a separate channel.',
    situation: 'Password protection adds access control to forms, statements, client files, and other PDFs that need to be stored or transferred. It helps while the file is closed, but an authorized recipient can still copy information they are able to view.',
    preparation: 'Remove pages the recipient does not need and redact content they should never receive. Choose a long, unique passphrase that is not based on a name, date, or account password. Keep an unprotected source in secure storage.',
    decisions: 'Use an open password when the file should not be viewed without authorization. Save a new protected output and test it in a normal reader. Send the password by phone or another channel instead of placing it beside the attachment.',
    mistakes: ['A short password based on the document title can be easy to guess.', 'Sending the file and password in one email creates one point of failure.', 'Overwriting the only unprotected source can create a recovery problem if the password is lost.'],
    related: ['redact', 'sign', 'decrypt'],
  },
  {
    id: 'decrypt', slug: 'how-to-unlock-a-pdf-you-own', title: 'How to Unlock a PDF You Own',
    description: 'Remove password protection from an authorized PDF working copy, handle the password carefully, and protect the unencrypted output.',
    situation: 'Unlocking is useful when an owned document must be merged, archived, printed, or processed by software that cannot repeatedly request a password. It requires the correct password and permission to create an unprotected copy.',
    preparation: 'Confirm that you are allowed to remove the protection and keep the original secured file. Enter the password privately and choose a safe working location. Remember that the output will no longer have the same access barrier.',
    decisions: 'Create the unprotected copy only for as long as the workflow needs it. Decide whether the final document should receive a new password after editing or merging. Use filenames that clearly separate protected and working versions.',
    mistakes: ['Unlocking a file does not grant rights to content you were not allowed to use.', 'Leaving an unprotected copy in Downloads can expose it to other device users.', 'Forgetting which copy is protected can lead to sending the wrong attachment.'],
    related: ['merge', 'compress', 'encrypt'],
  },
  {
    id: 'sign', slug: 'how-to-sign-a-pdf', title: 'How to Add a Signature to a PDF',
    description: 'Place a visual signature carefully, confirm the correct page and signer, and understand when a certificate-based signature is required.',
    situation: 'A visual signature is useful for acknowledgements, permission forms, simple approvals, and documents where the recipient accepts an image of a signature. It may not satisfy a legal or organizational process that requires identity verification and a digital certificate.',
    preparation: 'Read the signing instructions, confirm the correct document version, and find every required field. Use a clear signature image with a clean background. Finish content changes before signing so the approved version does not change afterward.',
    decisions: 'Size and place the signature within its intended field without covering dates or nearby text. Add the date or printed name when required. Ask the recipient whether a visual mark is enough or an approved electronic signing platform must be used.',
    mistakes: ['Signing an outdated draft can approve the wrong terms.', 'A signature image placed over other text can make the form unclear.', 'Calling a visual signature a cryptographic digital signature can misrepresent what the file proves.'],
    related: ['encrypt', 'merge', 'compress'],
  },
  {
    id: 'batch', slug: 'how-to-batch-process-pdf-files', title: 'How to Batch Process PDF Files',
    description: 'Prepare a group of PDFs, test settings on samples, keep filenames traceable, and review enough outputs to trust a repeated process.',
    situation: 'Batch processing saves time when many PDFs need the same predictable action. It suits mechanical work such as applying one setting to a known group, but it is less suitable for decisions that depend on each page\'s meaning or layout.',
    preparation: 'Copy the source set into a working folder, count the files, and inspect a few different examples. Separate unusual PDFs before running the batch. Choose an output folder and naming pattern that will not overwrite the originals.',
    decisions: 'Test the exact settings on a small sample first. Decide how errors should be handled and whether one failed file should stop the group. Compare output count with input count, then review files from the beginning, middle, and end.',
    mistakes: ['Testing only the easiest file can hide a problem with scans, forms, or unusual page sizes.', 'Overwriting sources removes the clean recovery path when one setting is wrong.', 'Assuming every completed output is correct skips the quality control that makes automation trustworthy.'],
    related: ['compress', 'watermark', 'wcag'],
  },
  {
    id: 'wcag', slug: 'how-to-check-pdf-accessibility', title: 'How to Check a PDF for Accessibility',
    description: 'Use automated findings as a starting point, then review headings, reading order, alt text, tables, forms, contrast, and keyboard use.',
    situation: 'An accessibility check can identify missing metadata, untagged content, and other problems that may affect people using screen readers, keyboards, zoom, or high contrast settings. No automated score can decide whether every part of a document makes sense.',
    preparation: 'Use the source document when it is available because headings, lists, tables, and alt text are easier to correct there. Set the document title and language, then save a working PDF. Know the audience and any standard the publisher must follow.',
    decisions: 'Review the tag structure and reading order, especially on pages with columns or sidebars. Check meaningful images, table headers, form labels, link text, contrast, and keyboard order. Test important public documents with assistive technology and real users when possible.',
    mistakes: ['Treating a passing automated result as a compliance certificate skips manual problems.', 'Adding OCR to a scan creates text but does not create headings or a logical reading order.', 'Fixing only visual appearance can leave the tag structure confusing for a screen reader.'],
    related: ['edit', 'pdf-to-text', 'pdf-to-image'],
  },
]

const toolById = new Map(tools.map((tool) => [tool.id, tool]))
const link = (tool) => `<a href="${tool.canonicalPath}">${tool.name}</a>`

function buildToolGuide(profile) {
  const tool = toolById.get(profile.id)
  const relatedTools = profile.related.map((id) => toolById.get(id))
  const toolLink = link(tool)
  const [firstRelated, secondRelated, thirdRelated] = relatedTools.map(link)

  return {
    toolId: profile.id,
    richIntro: true,
    slug: profile.slug,
    title: profile.title,
    description: profile.description,
    published: profile.published || '2026-07-22',
    readTime: '10 min read',
    intro: `${toolLink} handles a focused document job inside the browser. This guide explains when that job makes sense, how to prepare the source, which choices matter, and how to review the exported copy before sending it to someone else.`,
    sections: [
      {
        title: `When ${tool.name} is useful`,
        paragraphs: [
          profile.situation,
          'Use the browser tool when the task matches that purpose and the source file is in your control. A focused action is usually easier to understand than a long workflow with steps the document does not need. Write down the expected result before opening the file, including the page count, filename, size limit, and any instructions from the recipient.',
        ],
      },
      {
        title: 'Prepare the source before making changes',
        paragraphs: [
          profile.preparation,
          'Keep the original in a separate folder and work on a copy. Open the source in a normal PDF reader, move through the full document, and note anything unusual such as scans, forms, comments, signatures, mixed page sizes, or uncommon fonts. This first check gives you something reliable to compare with the output.',
          'Load the working copy only after the source check. Browser processing means the supported document operation happens on your device. The file does not need to be sent to a PDFOmni processing server, although normal website resources, analytics, ads, and optional online features can still use internet requests.',
        ],
      },
      {
        title: 'Make the important choices before export',
        paragraphs: [
          profile.decisions,
          'Use settings that match the final destination rather than choosing the strongest or fastest option automatically. A school portal, office archive, printed packet, and phone-readable copy can have different needs. The correct result is the one that remains clear and meets the instructions, not the one with the most dramatic setting.',
          'Complete the change and export a new file. Give it a name that explains its status, such as review or submitted, instead of final2. Do not delete the source or overwrite the only copy. If the result is wrong, return to the clean source rather than repeatedly processing an already changed output.',
        ],
      },
      {
        title: 'Mistakes that are easy to miss',
        paragraphs: profile.mistakes.map((mistake) => `${mistake} Slow down around this point and compare the result with the source instead of assuming a completed progress bar means the document is ready.`),
      },
      {
        title: 'Use related tools only when the document needs them',
        paragraphs: [
          `After using ${toolLink}, ${firstRelated} can handle the next part of the workflow when that change is actually required. Open the downloaded copy, check it first, and then use it as the input. This keeps each step understandable and makes it easier to find where a problem began.`,
          `${secondRelated} is another useful option when the document needs a different kind of preparation. Keep a clear filename between steps and avoid stacking changes just because the buttons are available. Every extra export creates another version that must be reviewed.`,
          `Use ${thirdRelated} when its purpose matches the final delivery. These tools are linked directly because they often belong near this task, but they are not mandatory. A short workflow with one correct action is better than a long workflow that changes parts of the PDF for no reason.`,
        ],
      },
      {
        title: 'Privacy and device limits',
        paragraphs: [
          'The core document operation runs locally in the browser. That can be useful for private school records, applications, invoices, contracts, and personal documents because an unnecessary server copy is removed from the workflow. Local processing does not protect a file from an unsafe computer, an untrusted browser extension, or a recipient who should not have received it.',
          'Large and complicated PDFs use the memory and processor of the device in front of you. A short digital report may finish quickly, while a high-resolution scan with hundreds of pages can take longer or exceed the practical limits of an older phone. Close other demanding tabs, keep a backup, and use approved offline software when school or workplace policy requires it.',
        ],
      },
      {
        title: 'Review the exact downloaded file',
        paragraphs: profile.review || [
          'Close the working preview and reopen the downloaded PDF. Confirm the filename, page count, order, orientation, smallest text, images, forms, links, and any area changed by the tool. Check at normal zoom and high zoom. Open the file in a second reader when it is going to an official portal or another important destination.',
          'Compare the export with the source and the written goal from the beginning. A successful download only proves that a file was created. It does not prove that a signature is on the right page, a redaction removed its text, a table stayed readable, or a page range contains every required sheet. The final review is part of the task, not an optional extra.',
          'Keep the source and reviewed output until the recipient accepts the document. If another change is needed, choose the relevant linked tool and start from the best available version. The purpose of a focused browser action is to make one PDF job simpler while leaving you in control of the document and its versions.',
        ],
      },
      {
        title: 'Leave a clear handoff for the next person',
        paragraphs: [
          'A reviewed file is easier to trust when the next person can tell what changed. Keep the final filename plain, record the date, and add a short note when pages were removed, reordered, compressed, converted, or protected. The note does not need to become a formal report. One or two sentences can explain the source used, the action completed, and any part that still deserves attention. This is especially useful for group assignments, office packets, family records, and documents that move through several reviewers. It prevents someone from reopening an older copy and repeating work that was already checked. Do not place passwords or private details in the note. Store those through the approved channel, and keep the handoff focused on the document version and the review that was completed.',
        ],
      },
    ],
    checklist: [
      'Read the recipient instructions and write down the required result before choosing a file.',
      'Keep the untouched source in a separate folder and make changes to a working copy.',
      'Open the source and record its page count, size, orientation, and any unusual content.',
      'Choose settings for the final use instead of selecting the strongest option automatically.',
      'Export with a filename that clearly separates the new version from the original.',
      'Reopen the exact downloaded file rather than judging only from the working preview.',
      'Compare changed pages with the source at both normal zoom and high zoom.',
      'Test important links, forms, signatures, text selection, or security settings when relevant.',
      'Use another PDF reader for an important submission or a file with unusual content.',
      'Keep the reviewed output and source until the document has been accepted.',
    ],
    related: [
      { href: tool.canonicalPath, label: `Open ${tool.name}` },
      ...relatedTools.map((relatedTool) => ({ href: relatedTool.canonicalPath, label: `Open ${relatedTool.name}` })),
    ],
  }
}

export const toolGuides = profiles.map(buildToolGuide)
