const defaults = {
  privacyAngle: 'PDFOmni processes files in your browser, so the document bytes stay on your device instead of being uploaded to a remote PDF server.',
  advanced: 'After finishing this tool, you can continue into other PDFOmni workflows such as editing, signing, redacting, compressing, or using the AI Copilot with local document context.',
  safetyFaq: {
    question: 'Is it safe to use this PDF tool online?',
    answer: 'Yes. The core PDF workflow runs locally in your browser, so your PDF is processed on your device and is not uploaded by PDFOmni for server-side handling.',
  },
}

const categoryNotes = {
  organize: [
    'Page organization changes the structure of a document, so it helps to keep the original and export a new copy. Check the page count before and after the change. A missing attachment or an extra blank scan is easier to catch when you know the expected total.',
    'Use page thumbnails to plan the order, then open the downloaded file at normal size. Thumbnails can hide sideways text, clipped margins, duplicated forms, and pages that look almost identical. Review every boundary where one source document ends and another begins.',
    'If the final PDF is going to a portal, check its page and file-size rules before adding extra material. A clear packet contains what the recipient needs in an order they can follow. More pages do not automatically make a submission more complete.',
  ],
  'convert-to': [
    'A conversion creates a PDF view of the source, not another fully editable copy of the original format. Keep the Word file, spreadsheet, image, or HTML source because it is usually the best place to make later content changes.',
    'Compare headings, page breaks, tables, links, images, and special characters after export. Fonts and browser layout rules can change wrapping, especially when the source uses uncommon fonts or a page size that does not match the PDF settings.',
    'For an official submission, reopen the downloaded PDF in a normal reader instead of relying only on the preview. Check the filename, page count, orientation, and smallest text. The converted file should be judged by what the recipient will actually open.',
  ],
  'convert-from': [
    'Extraction changes how the document can be reused. Images preserve the look of a page but not its selectable text. Plain text is easy to search and quote but does not preserve columns, spacing, or the visual meaning of a layout.',
    'Scanned pages may not contain stored text at all. If extraction returns an empty or confused result, the PDF may need optical character recognition. Compare important names, numbers, and quotations with the page image before relying on the output.',
    'Use the smallest output that fits the next job. A PNG can be useful for a sharp diagram, a JPG can be smaller for a photograph, and plain text works well for notes. Keep the original PDF as the reference when layout or evidence matters.',
  ],
  edit: [
    'PDF editing is different from editing the source document that created the PDF. Text may be split into small objects, fonts can be embedded with unusual character maps, and a scanned page may only be an image. Keep the original and expect complicated files to need a closer review.',
    'When removing private information, use a real redaction workflow instead of covering it with a shape or changing the text color. When cropping, check that the operation removes only the intended page area and does not hide information that another person still needs.',
    'Inspect the exported copy at high zoom around every changed area. Check nearby lines, table borders, word spacing, image quality, and selectable text. The editing canvas is a working view, while the downloaded PDF is the result that matters.',
  ],
  security: [
    'Security tools should be used only on documents you own or have permission to handle. Unlocking is not a way to bypass access you were never given, and placing a visual signature is not automatically the same as a certificate-based digital signature.',
    'A password-protected PDF is only as safe as its password and delivery method. Use a long, unique passphrase, store it in a password manager, and send it through a different channel from the document. PDFOmni cannot recover a password that everyone loses.',
    'Review the final file before sharing it. Confirm that protection opens with the intended password, redacted information cannot be searched or copied, and the signature appears on the correct page. Follow the receiving organization\'s rules when a legal or official process requires a specific kind of security.',
  ],
  advanced: [
    'Automated checks and batch actions are most useful for repeated mechanical work. They do not replace human decisions about privacy, accessibility, layout, or whether a document is ready to publish. Use the output as a starting point for review.',
    'Test a workflow on copies of a few representative files before running a large group. PDFs that look similar can contain different fonts, forms, scans, or permissions. A small test makes it easier to notice a setting that does not fit every document.',
    'Keep a record of the settings that worked and inspect the downloaded files. For accessibility, combine automated findings with keyboard and screen-reader testing. For batch work, compare file counts and open samples from the beginning, middle, and end of the output set.',
  ],
}

const relatedTools = {
  merge: [{ href: '/reorder', label: 'Reorder the merged pages' }, { href: '/compress', label: 'Compress the finished packet' }, { href: '/page-numbers', label: 'Add page numbers' }],
  split: [{ href: '/merge', label: 'Merge selected documents' }, { href: '/compress', label: 'Compress extracted pages' }, { href: '/redact', label: 'Redact before sharing' }],
  reorder: [{ href: '/merge', label: 'Merge more documents' }, { href: '/rotate', label: 'Rotate sideways pages' }, { href: '/page-numbers', label: 'Number the final order' }],
  compress: [{ href: '/split', label: 'Remove unneeded pages' }, { href: '/merge', label: 'Build one packet' }, { href: '/sign', label: 'Sign the final copy' }],
  rotate: [{ href: '/reorder', label: 'Reorder corrected pages' }, { href: '/crop', label: 'Crop scan borders' }, { href: '/pdf-to-text', label: 'Extract stored text' }],
  'page-numbers': [{ href: '/reorder', label: 'Fix the page order first' }, { href: '/watermark', label: 'Add a watermark' }, { href: '/sign', label: 'Sign the document' }],
  'word-to-pdf': [{ href: '/merge', label: 'Merge supporting files' }, { href: '/compress', label: 'Reduce the PDF size' }, { href: '/edit-pdf', label: 'Edit the converted PDF' }],
  'excel-to-pdf': [{ href: '/crop', label: 'Trim extra margins' }, { href: '/merge', label: 'Add the PDF to a report' }, { href: '/watermark', label: 'Watermark a review copy' }],
  'image-to-pdf': [{ href: '/rotate', label: 'Correct page orientation' }, { href: '/crop', label: 'Remove scan borders' }, { href: '/compress', label: 'Reduce scan size' }],
  'html-to-pdf': [{ href: '/edit-pdf', label: 'Edit the generated PDF' }, { href: '/compress', label: 'Compress it for sharing' }, { href: '/merge', label: 'Add it to another document' }],
  'pdf-to-image': [{ href: '/image-to-pdf', label: 'Build a PDF from images' }, { href: '/pdf-to-text', label: 'Extract the text instead' }, { href: '/crop', label: 'Crop page margins' }],
  'pdf-to-word': [{ href: '/word-to-pdf', label: 'Convert Word back to PDF' }, { href: '/pdf-to-text', label: 'Extract plain PDF text' }, { href: '/guides/how-to-convert-pdf-to-word', label: 'Read the PDF to Word guide' }],
  'pdf-to-text': [{ href: '/wcag-check', label: 'Review accessibility' }, { href: '/edit-pdf', label: 'Edit PDF text' }, { href: '/guides/work-with-scanned-pdfs-and-ocr', label: 'Learn about scans and OCR' }],
  edit: [{ href: '/redact', label: 'Redact private content' }, { href: '/sign', label: 'Add a signature' }, { href: '/compress', label: 'Compress the edited copy' }],
  watermark: [{ href: '/sign', label: 'Sign the document' }, { href: '/page-numbers', label: 'Add page numbers' }, { href: '/protect', label: 'Protect the shared copy' }],
  redact: [{ href: '/split', label: 'Share only needed pages' }, { href: '/protect', label: 'Protect the redacted copy' }, { href: '/guides/redact-a-pdf-safely', label: 'Read the redaction guide' }],
  crop: [{ href: '/rotate', label: 'Rotate scanned pages' }, { href: '/compress', label: 'Compress the cropped PDF' }, { href: '/pdf-to-image', label: 'Export pages as images' }],
  encrypt: [{ href: '/sign', label: 'Sign before protecting' }, { href: '/redact', label: 'Remove private details' }, { href: '/guides/password-protect-and-share-pdfs', label: 'Read the safe sharing guide' }],
  decrypt: [{ href: '/merge', label: 'Merge the working copy' }, { href: '/compress', label: 'Compress the unlocked copy' }, { href: '/protect', label: 'Protect a final version' }],
  sign: [{ href: '/protect', label: 'Protect the signed PDF' }, { href: '/merge', label: 'Add supporting documents' }, { href: '/compress', label: 'Reduce the final size' }],
  batch: [{ href: '/workflow', label: 'Build a reusable workflow' }, { href: '/compress', label: 'Compress one PDF' }, { href: '/guides/build-a-better-pdf-workflow', label: 'Plan a better workflow' }],
  wcag: [{ href: '/edit-pdf', label: 'Edit the document' }, { href: '/pdf-to-text', label: 'Inspect extracted text' }, { href: '/guides/make-pdfs-wcag-accessible', label: 'Read the accessibility guide' }],
}

function getCompetitivePositioning(tool) {
  return `${tool.name} runs as a local browser workflow. This avoids an unnecessary document upload, while leaving the user responsible for checking the downloaded result and following any rules that apply to the file.`
}

export const toolSeo = {
  merge: {
    h1: 'Merge PDF Files Locally - Fast, Free, and Private',
    intro: 'Combine multiple PDF files into a single organized document without sending them to a server. The merge tool is built for quick browser-based document assembly, whether you are joining reports, receipts, scans, contracts, or school files.',
    steps: ['Select or drag two or more PDF files into the upload area.', 'Review the file order and rearrange the documents if needed.', 'Export one combined PDF directly from your browser session.'],
    why: 'Because the merge happens locally, you avoid the slow upload-and-wait flow common on server-based PDF sites. Large files can be joined without exposing confidential pages to a remote processor.',
    advanced: 'Once the merged file is ready, you can move into page reordering, compression, signing, watermarking, or AI Copilot analysis without leaving the PDFOmni workspace.',
    useCases: ['Combining signed forms into one packet', 'Joining scanned receipts for expense reports', 'Merging project chapters or client deliverables'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I change the order before merging?', answer: 'Yes. Add the PDFs, arrange them in the order you want, and then export the final merged document.' },
      { question: 'Does merging reduce PDF quality?', answer: 'No intentional quality reduction is applied. Pages are copied into one file, so the original visual content is preserved as much as the browser PDF engine allows.' },
    ],
  },
  split: {
    h1: 'Split PDF Pages Locally - Extract Pages Without Uploads',
    intro: 'Split a PDF into smaller files or extract only the pages you need. This is useful when a long PDF contains one section, invoice, chapter, or form that needs to be shared separately.',
    steps: ['Drop your PDF into the upload box.', 'Enter the page range or choose the pages you want to extract.', 'Download the split PDF output instantly.'],
    why: 'The page extraction happens on your computer, so sensitive pages are not sent through an upload queue. You get fast page splitting while keeping the original PDF private.',
    advanced: 'After splitting a document, you can compress the extracted pages, add page numbers, sign the result, or use the AI Copilot to summarize just the smaller section.',
    useCases: ['Extracting one chapter from an ebook or manual', 'Sharing only selected contract pages', 'Creating smaller PDFs from large scans'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I split only specific page ranges?', answer: 'Yes. Use page ranges to export the exact pages you need instead of saving the full document.' },
      { question: 'Will the original PDF be changed?', answer: 'No. PDFOmni creates a new output file in your browser and leaves the original file untouched.' },
    ],
  },
  reorder: {
    h1: 'Reorder PDF Pages Privately in Your Browser',
    intro: 'Rearrange PDF pages with a simple drag-and-drop workflow. It is designed for fixing scanned documents, moving cover pages, sorting appendices, and cleaning up page order before sharing.',
    steps: ['Upload your PDF locally in the browser.', 'Drag pages into the correct order in the page grid.', 'Download the reordered PDF file.'],
    why: 'Reordering pages should not require uploading a confidential document. PDFOmni keeps the page arrangement process local so you can correct files quickly and privately.',
    advanced: 'When the page order is right, you can continue with compression, watermarking, signing, page numbering, or AI-assisted review inside the same PDF toolkit.',
    useCases: ['Fixing scans that were saved out of order', 'Moving a cover sheet to the front', 'Preparing packets before emailing or printing'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I reorder every page manually?', answer: 'Yes. The tool is built around page thumbnails so you can move pages into the exact sequence you want.' },
      { question: 'Does reordering delete any pages?', answer: 'No. Reordering changes the page sequence in the exported copy unless you intentionally use another tool to remove pages.' },
    ],
  },
  compress: {
    h1: 'Compress PDF Files Locally - Reduce Size Without Uploading',
    intro: 'Compress PDF files to make them easier to email, upload, archive, or share. The compressor runs in the browser and focuses on reducing file size while giving you control over the output target.',
    steps: ['Select your PDF from the upload area.', 'Choose a compression target or quality level.', 'Download the optimized PDF when the analysis and compression finish.'],
    why: 'Server compressors require uploading the whole document before any optimization starts. PDFOmni keeps the work on your device, which is especially helpful for private files, large PDFs, and slow connections.',
    advanced: 'After compression, you can use PDFOmni to merge the smaller file with other documents, redact sensitive information, add a signature, or ask the AI Copilot about the compressed PDF content.',
    useCases: ['Shrinking PDFs for email attachments', 'Meeting upload size limits on forms and portals', 'Reducing local storage used by large scanned files'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Will compressing a PDF ruin the quality?', answer: 'Compression can reduce image detail depending on the target size, but you can choose settings that balance quality and file size.' },
      { question: 'Can I compress a large PDF?', answer: 'Yes, though very large documents depend on your browser memory and device performance because the work happens locally.' },
    ],
  },
  rotate: {
    h1: 'Rotate PDF Pages Online - Local and Secure',
    intro: 'Rotate sideways or upside-down PDF pages directly in your browser. This is useful for scanned documents, phone photos saved as PDFs, or mixed-orientation files that need quick cleanup.',
    steps: ['Upload the PDF you want to rotate.', 'Choose individual pages or apply rotation to the full document.', 'Export a corrected PDF with the new page orientation.'],
    why: 'Rotation is handled locally, so you do not have to upload personal IDs, forms, scans, or contracts just to fix orientation. The output is created from your browser session.',
    advanced: 'After rotating pages, you can reorder them, add page numbers, compress the corrected file, or continue into signing and editing tools.',
    useCases: ['Correcting scanned pages from a copier', 'Fixing phone-generated PDFs', 'Preparing mixed-orientation documents for printing'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I rotate only one page?', answer: 'Yes. You can rotate selected pages instead of applying the same change to the whole PDF.' },
      { question: 'Does rotation affect text selection?', answer: 'The page orientation is updated in the exported PDF while preserving the document content as much as possible.' },
    ],
  },
  'page-numbers': {
    h1: 'Add Page Numbers to a PDF Locally',
    intro: 'Add clear page numbers to reports, packets, drafts, and long PDFs without uploading the document. Page numbering helps readers reference sections and keeps printed files easier to navigate.',
    steps: ['Upload your PDF into the browser.', 'Choose the numbering style, position, and starting number.', 'Download the PDF with page numbers applied.'],
    why: 'PDFOmni applies page numbers locally, so internal reports, legal packets, and private drafts do not need to leave your computer for a simple formatting change.',
    advanced: 'You can combine page numbering with merging, reordering, watermarking, signing, or compression to prepare a polished final document.',
    useCases: ['Numbering client packets before review', 'Adding references to study notes or manuals', 'Preparing PDFs for printing and physical binders'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I choose where page numbers appear?', answer: 'Yes. Use the page number settings to place numbering where it fits your document layout.' },
      { question: 'Can page numbers start from a custom number?', answer: 'Yes. The tool supports changing the starting number for documents that continue from another file.' },
    ],
  },
  'word-to-pdf': {
    h1: 'Convert Word to PDF in Your Browser',
    intro: 'Convert DOCX documents into PDF files locally for easier sharing, printing, and archiving. The tool is designed for quick document conversion without a server upload step.',
    steps: ['Choose a Word document from your device.', 'Let the browser prepare the PDF output.', 'Download the converted PDF file.'],
    why: 'Local conversion helps keep drafts, resumes, internal memos, and client documents private. You avoid sending the source Word file to a remote converter just to create a PDF.',
    advanced: 'After conversion, you can merge the PDF with attachments, compress it, add page numbers, watermark it, or use AI Copilot to inspect the resulting document.',
    useCases: ['Saving resumes and letters as PDFs', 'Preparing DOCX reports for upload portals', 'Creating shareable copies of office documents'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does the Word file upload to a server?', answer: 'No. PDFOmni performs the conversion in the browser as part of its local-first PDF workflow.' },
      { question: 'Will complex formatting always match perfectly?', answer: 'Most common document layouts convert well, but very complex Word features can vary depending on browser rendering support.' },
    ],
  },
  'excel-to-pdf': {
    h1: 'Convert Excel to PDF Privately',
    intro: 'Turn spreadsheets into PDF documents for sharing, printing, or submitting. The Excel to PDF tool keeps the workflow local while making tabular data easier to distribute.',
    steps: ['Upload an Excel or CSV file.', 'Preview or prepare the spreadsheet output.', 'Download the finished PDF from your browser.'],
    why: 'Spreadsheets often contain financial, customer, or operational details. Local conversion helps you create PDF copies without sending workbook data to a third-party server.',
    advanced: 'Once the spreadsheet is a PDF, you can compress it, add a watermark, merge it into a report, or open it in the editor for additional markup.',
    useCases: ['Exporting invoices or budgets', 'Sharing read-only spreadsheet reports', 'Preparing tables for email or print'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I convert CSV files too?', answer: 'Yes. The tool accepts common spreadsheet formats including CSV where supported by the app workflow.' },
      { question: 'Will formulas remain editable?', answer: 'No. The output is a PDF view of the spreadsheet, so formulas become document content rather than editable spreadsheet cells.' },
    ],
  },
  'image-to-pdf': {
    h1: 'Convert Images to PDF Locally',
    intro: 'Create a PDF from JPG, PNG, WebP, BMP, or similar image files. This is useful for turning photos, receipts, scans, screenshots, and design exports into one shareable PDF.',
    steps: ['Select one or more images from your device.', 'Arrange the images in the order you want.', 'Export them as a single PDF file.'],
    why: 'Image-to-PDF conversion runs in the browser, so photos of private documents or receipts do not need to be uploaded to a cloud converter.',
    advanced: 'After creating the PDF, you can merge it with other files, compress it, add page numbers, or use the editor to place text, shapes, and signatures.',
    useCases: ['Combining receipt photos into one file', 'Turning screenshots into a PDF handout', 'Creating PDF scans from phone images'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I convert multiple images at once?', answer: 'Yes. Add multiple images and export them together as one PDF.' },
      { question: 'Will the image quality change?', answer: 'The PDF uses your image data, though final file size and display quality can depend on image dimensions and browser processing.' },
    ],
  },
  'html-to-pdf': {
    h1: 'Convert HTML to PDF in the Browser',
    intro: 'Turn pasted HTML or uploaded HTML files into PDF documents. It is a quick way to save web content, templates, receipts, or simple reports as portable files.',
    steps: ['Paste HTML content or upload an HTML file.', 'Preview or prepare the document in the browser.', 'Download the generated PDF.'],
    why: 'HTML conversion is handled locally, which keeps draft templates and internal content away from server-side converters. It also removes the delay of uploading source files first.',
    advanced: 'The generated PDF can be compressed, merged, signed, watermarked, or reviewed with other PDFOmni tools after conversion.',
    useCases: ['Saving simple web templates as PDFs', 'Creating printable HTML reports', 'Archiving receipts or generated pages'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I upload an HTML file?', answer: 'Yes. You can paste HTML or use the upload mode for local HTML files.' },
      { question: 'Will external website styling always load?', answer: 'External assets can depend on browser access and CORS rules, so self-contained HTML usually produces the most reliable result.' },
    ],
  },
  'pdf-to-image': {
    h1: 'Convert PDF Pages to Images Locally',
    intro: 'Export PDF pages as image files for previews, thumbnails, presentations, or quick sharing. The conversion is done on your device through the browser.',
    steps: ['Upload the PDF you want to convert.', 'Choose image settings and page output options.', 'Download the exported images.'],
    why: 'Because pages are rendered locally, you can convert private PDFs into images without uploading the document to a remote rendering service.',
    advanced: 'After exporting images, you can also convert images back into a new PDF, compress the original file, or use AI Copilot to summarize the source document.',
    useCases: ['Creating thumbnails for documents', 'Exporting pages for presentations', 'Saving PDF pages as shareable images'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I convert every page?', answer: 'Yes. You can export pages from the PDF as images depending on the selected settings.' },
      { question: 'What image formats are supported?', answer: 'PDFOmni supports common browser image output formats such as PNG or JPG where available in the tool.' },
    ],
  },
  'pdf-to-word': {
    h1: 'Convert PDF to Word Online for Free in Your Browser',
    intro: 'Convert PDF into Word as an editable DOCX file without sending the document to a conversion server. This free PDF to Word converter analyzes text, fonts, images, links, tables, and page geometry locally in the browser, then builds a Word document that keeps the original layout as closely as the format allows.',
    steps: [
      'Choose a PDF from your device or drop it into the converter.',
      'Review the filename, page count, text type, and page previews before starting.',
      'Convert PDF to Word online while the browser processes each page locally.',
      'Download the DOCX file, open it in Word or another compatible editor, and inspect every important page.',
    ],
    why: 'A PDF is designed to preserve a finished page, while Word is designed for editing. PDFOmni reconstructs the page as Word content instead of sending the file to a remote PDF converter to Word service. It is useful for reports, course notes, resumes, forms, research papers, manuals, and older documents when the original DOCX is no longer available.',
    advanced: 'For the best result, start with a digital PDF that contains selectable text. The converter places editable text, images, links, detected tables, and visual page elements into a DOCX package. Complex equations, unusual fonts, layered artwork, and scans may need selective image-based fallbacks because Word and PDF describe pages in very different ways. After reviewing the DOCX, use Word to PDF if you need a new fixed-layout copy.',
    useCases: [
      'Recovering an editable draft when only the PDF remains',
      'Updating a resume, report, assignment, or letter',
      'Reusing tables, text, images, and links from an owned document',
      'Preparing a PDF for comments or revision in Microsoft Word',
    ],
    notes: [
      'A PDF to DOCX conversion is a reconstruction, not a return to the original authoring file. The PDF may store each line, glyph, image, and drawing at a fixed coordinate without recording paragraphs or styles. PDFOmni reads those objects and rebuilds a Word page with editable elements where it can. Keep the PDF beside the DOCX so you can compare line wrapping, columns, headers, footnotes, tables, and page breaks.',
      'Digital PDFs usually produce more editable text than scans. An image-only scan does not contain ordinary characters, so a PDF to Word converter can preserve that page as an image unless reliable text recognition is available. A visual fallback keeps the page readable, but words inside the image are not automatically editable. If editing every sentence matters, use a clean source scan and expect to proofread OCR results.',
      'Fonts affect both appearance and geometry. When embedded font data is available, the converter carries it into the Word package when possible. If Word substitutes another font, character widths can change and a line may wrap differently. Open the downloaded file on the computer where it will be edited, check mathematical symbols and small labels, and confirm that no substituted font has moved content outside its page area.',
    ],
    searchLanguage: [
      'The basic job is often described as “convert pdf into word,” “convert to word,” “pdf word,” “pdf convert to word,” or simply “convert pdf to word.” A useful pdf to word converter should explain which Word format it creates and how much of the result stays editable.',
      'People looking for a browser option may type “pdf to word online converter,” “convert pdf to word online,” or “pdf converter to word.” Here, online describes a tool opened from a website. The document conversion itself still runs on the user’s device.',
      'Cost-focused searches include “pdf to word free converter,” “free pdf to word converter,” “free pdf converter,” “pdf to word free,” “pdf to word converter free,” and “convert pdf to word free.” PDFOmni does not require an account or a per-download payment for this conversion.',
      'The output format also changes the wording. “pdf to doc,” “pdf to docx,” and “pdf a word” all refer to a Word document, but DOC and DOCX are not the same file type. PDFOmni creates DOCX, which is the current XML-based Word format. International searches such as “pdf en word” and “converter pdf em word” describe the same conversion in Spanish or Portuguese wording.',
      'Some searches include another product name, including “pdf to word converter ilovepdf,” “pdf a word ilovepdf,” “pdf to word i love pdf,” “pdf to word ilovepdf,” and “ilovepdf pdf to word.” PDFOmni is independent and is not affiliated with iLovePDF. These phrases are mentioned only to clarify that the document task is the same, while PDFOmni uses its own local browser conversion system.',
    ],
    faqs: [
      { question: 'Is this a free PDF to Word converter?', answer: 'Yes. PDFOmni lets you convert PDF to Word free in the browser without creating an account or paying for each download.' },
      { question: 'Does PDFOmni upload my PDF?', answer: 'The core conversion runs locally in your browser. The selected document is not sent to a PDFOmni document-processing server, although normal website files, analytics, ads, and optional online features can still make internet requests.' },
      { question: 'Can I convert a PDF to DOC or DOCX?', answer: 'The converter creates a DOCX file, which is the current Word document format. It does not create the older binary DOC format.' },
      { question: 'Will the Word document look exactly like the PDF?', answer: 'The converter aims to preserve page geometry, text, images, links, fonts, tables, and visual elements, but identical output cannot be guaranteed. PDF and Word use different layout systems, and office programs can render the same DOCX differently.' },
      { question: 'Can scanned PDFs become editable Word files?', answer: 'Scanned pages can be preserved visually. If a page has no usable text layer, it may be placed into Word as an image, so its words will not be fully editable without OCR.' },
      { question: 'What should I check after conversion?', answer: 'Compare the DOCX with the PDF page by page. Check page count, columns, small text, equations, tables, links, images, fonts, headers, footers, and any page that uses an unusual layout.' },
    ],
  },
  'pdf-to-text': {
    h1: 'Extract Text from PDF Files Privately',
    intro: 'Copy text out of PDF files without sending the document to an extraction service. This is useful for notes, quotes, reports, research, and quick content reuse.',
    steps: ['Upload a PDF with selectable text.', 'Let PDFOmni extract the document text locally.', 'Copy or download the extracted text output.'],
    why: 'Text extraction can involve sensitive contracts, records, or research files. Running the extraction locally keeps the PDF content in your browser session.',
    advanced: 'You can combine extracted text with AI Copilot analysis, convert pages to images, or use other PDFOmni tools to prepare the original document for sharing.',
    useCases: ['Pulling text from reports or manuals', 'Saving notes from PDFs', 'Copying content for search and review'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does this work on scanned PDFs?', answer: 'It works best on PDFs with embedded selectable text. Scanned image-only PDFs may need OCR before reliable text extraction.' },
      { question: 'Will formatting be preserved?', answer: 'The tool focuses on extracting readable text, so complex layout and columns may not match the original PDF exactly.' },
    ],
  },
  edit: {
    h1: 'Edit PDF Files Locally in Your Browser',
    intro: 'Edit PDF files directly in your browser. Modify text, move content, adjust images, add shapes, place signatures, and export a new PDF without sending the source document to a processing server.',
    steps: ['Open your PDF in the browser-based editor.', 'Edit PDF text, images, shapes, signatures, or annotations locally.', 'Export the edited PDF from your device.'],
    why: 'PDF editing often involves contracts, forms, invoices, resumes, IDs, business drafts, or personal records. PDFOmni keeps the workflow local while still offering true PDF stream editing, embedded-font handling, selectable text preservation, and practical page object editing in the browser.',
    advanced: 'After editing, you can continue into compression, redaction, signing, page organization, conversion, or AI Copilot document review without switching to an upload-first PDF service.',
    useCases: ['Correcting text or labels before sharing', 'Moving text and images in existing PDFs', 'Adding signatures, shapes, and annotations locally'],
    faqs: [
      { question: 'Is it safe to edit my PDF here?', answer: 'Yes. PDFOmni edits PDF content locally in your browser instead of uploading the file for server-side processing.' },
      { question: 'Can I edit PDF text for free?', answer: 'Yes. The PDFOmni editor supports free PDF editing for practical text, image, shape, and signature changes.' },
      { question: 'Can the editor change existing PDF text?', answer: 'It can edit many selectable text objects and can also add new text. PDFs use many different font and encoding systems, so always check the exported file after changing existing content.' },
    ],
  },
  watermark: {
    h1: 'Add a Watermark to PDF Files Locally',
    intro: 'Place text watermarks on PDF pages for drafts, approvals, internal reviews, or ownership marks. The watermark is applied in your browser without uploading the PDF.',
    steps: ['Upload the PDF you want to watermark.', 'Enter your watermark text and choose placement or style settings.', 'Export the watermarked PDF.'],
    why: 'Watermarking often applies to private drafts, business documents, or client work. PDFOmni keeps those files local while still giving you a quick branding and labeling workflow.',
    advanced: 'After watermarking, you can compress the result, sign it, merge it with other documents, or redact sensitive sections before sharing.',
    useCases: ['Marking PDFs as draft or confidential', 'Adding a company or project label', 'Preparing review copies for clients'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I customize the watermark text?', answer: 'Yes. You can enter the text you want and adjust the available watermark settings before exporting.' },
      { question: 'Does the watermark apply to every page?', answer: 'The tool is designed for applying watermark text across the PDF according to the selected settings.' },
    ],
  },
  redact: {
    h1: 'Redact PDF Content Securely in Your Browser',
    intro: 'Black out sensitive areas of a PDF and export a version intended for safer sharing. Use it for names, IDs, account numbers, addresses, and other private details.',
    steps: ['Upload your PDF locally.', 'Draw redaction boxes over the content you want to remove.', 'Export a redacted PDF copy.'],
    why: 'Redaction is privacy-sensitive by nature. PDFOmni keeps the workflow local so the unredacted source document is not uploaded to a server during processing.',
    advanced: 'After redaction, you can compress the safe copy, add a watermark, sign it, or use page tools to remove unrelated pages before sending.',
    useCases: ['Removing personal data before sharing', 'Preparing public copies of records', 'Hiding financial or legal details'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Is the redacted text still copyable?', answer: 'The redaction workflow is designed to remove covered text from the exported PDF rather than simply placing a visual box over it.' },
      { question: 'Should I review the exported file?', answer: 'Yes. Always open and inspect the exported PDF before sharing any redacted document.' },
    ],
  },
  crop: {
    h1: 'Crop PDF Pages Locally and Privately',
    intro: 'Crop PDF page edges to remove margins, scanner borders, headers, footers, or unwanted whitespace. The crop tool is useful for cleaning scanned files and focusing a page layout.',
    steps: ['Upload the PDF you want to crop.', 'Set the crop box visually or with available controls.', 'Download the cropped PDF copy.'],
    why: 'Cropping happens in the browser, so private scans and internal files do not need to be uploaded just to adjust page boundaries.',
    advanced: 'After cropping, you can rotate pages, compress the result, add page numbers, or open the file in the editor for text and shape annotations.',
    useCases: ['Removing scanner borders', 'Trimming whitespace around pages', 'Preparing cleaner PDFs for print or upload'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does cropping delete the original file?', answer: 'No. PDFOmni exports a new cropped copy and does not modify the original PDF on your device.' },
      { question: 'Can I apply the same crop to multiple pages?', answer: 'The crop workflow supports applying crop settings across pages where the tool controls allow it.' },
    ],
  },
  encrypt: {
    h1: 'Protect PDF Files with a Password Locally',
    intro: 'Add password protection to a PDF before sharing or archiving it. The protect tool helps restrict access to documents that need an extra layer of security.',
    steps: ['Upload the PDF you want to protect.', 'Enter and confirm the password settings.', 'Download the password-protected PDF.'],
    why: 'Password protection is applied in the browser, so you do not have to give an unprotected copy of the file to a server before securing it.',
    advanced: 'After protecting a PDF, you can keep using PDFOmni to organize other documents, compress safe copies, or prepare a signed version for distribution.',
    useCases: ['Securing forms before email', 'Protecting client documents', 'Adding a password to archived records'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can PDFOmni recover the password later?', answer: 'No. Keep your password somewhere safe because PDFOmni does not store it for you.' },
      { question: 'Is password protection the same as encryption?', answer: 'Password protection uses PDF security features to restrict access, but you should still share passwords carefully.' },
    ],
  },
  decrypt: {
    h1: 'Unlock PDF Files Locally When You Know the Password',
    intro: 'Remove password protection from PDFs you are allowed to access. This helps when you need a copy that is easier to archive, merge, print, or process.',
    steps: ['Upload the protected PDF.', 'Enter the correct password in your browser.', 'Download the unlocked PDF copy.'],
    why: 'Unlocking happens locally, so the protected file and password do not need to be sent to a remote unlock service.',
    advanced: 'After unlocking, you can merge, split, compress, redact, sign, or analyze the document with PDFOmni tools.',
    useCases: ['Preparing owned files for archiving', 'Removing protection from internal documents', 'Making a document easier to merge or compress'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can this unlock a PDF without the password?', answer: 'No. You need the correct password and the right to access the document.' },
      { question: 'Is the original protected PDF changed?', answer: 'No. The tool creates a new unlocked output file and leaves the original untouched.' },
    ],
  },
  sign: {
    h1: 'Sign PDF Files Locally in Your Browser',
    intro: 'Add a signature image to PDF documents without uploading them. This is built for quick approvals, forms, acknowledgements, and lightweight signing workflows.',
    steps: ['Upload the PDF you need to sign.', 'Add or place your signature image on the page.', 'Export the signed PDF file.'],
    why: 'Signing often involves personal or business documents. PDFOmni keeps the PDF and signature asset in your browser session instead of sending them to a signing server.',
    advanced: 'After signing, you can compress the final PDF, merge it with supporting documents, or watermark a review copy.',
    useCases: ['Signing forms and acknowledgements', 'Adding approval marks to documents', 'Preparing PDFs for email submission'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Is this a cryptographic digital signature?', answer: 'This tool is for placing a visual signature image, not for certificate-based digital signing.' },
      { question: 'Can I move the signature before exporting?', answer: 'Yes. Place and adjust the signature visually before downloading the signed PDF.' },
    ],
  },
  batch: {
    h1: 'Batch Process PDF Files Locally',
    intro: 'Process multiple PDFs in one workflow instead of repeating the same action file by file. Batch processing is useful for repetitive document cleanup and preparation tasks.',
    steps: ['Upload the PDFs you want to process together.', 'Choose the batch action and settings.', 'Download the processed output files.'],
    why: 'Batch work can involve many private documents. PDFOmni keeps the processing local so you can handle groups of files without sending them through a server queue.',
    advanced: 'Use batch processing with other PDFOmni workflows such as compression, protection, page organization, or AI-assisted document review when you need a larger document pipeline.',
    useCases: ['Preparing many PDFs for upload', 'Applying repeated cleanup steps', 'Processing document sets for a client or class'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Can I process multiple files at once?', answer: 'Yes. The batch tool is built for handling more than one PDF in a single workflow.' },
      { question: 'Will batch processing be slower on large files?', answer: 'It can be, because the work uses your browser and device resources instead of a remote server.' },
    ],
  },
  wcag: {
    h1: 'Check PDF Accessibility Locally',
    intro: 'Run a PDF accessibility-oriented check to identify issues that may affect readers using assistive technology. It helps you review documents before publishing or sharing them widely.',
    steps: ['Upload the PDF you want to inspect.', 'Run the accessibility check in the browser.', 'Review the findings and decide what needs fixing.'],
    why: 'Accessibility review can involve unpublished or internal files. A local-first check lets you inspect documents without uploading draft content to a third-party scanner.',
    advanced: 'After reviewing issues, you can use PDFOmni tools to edit, add text, organize pages, compress the file, or prepare a corrected version for distribution.',
    useCases: ['Checking public documents before upload', 'Reviewing forms and reports', 'Finding accessibility problems in shared PDFs'],
    faqs: [
      defaults.safetyFaq,
      { question: 'Does this guarantee WCAG compliance?', answer: 'No automated check can guarantee full compliance. Use the results as a practical review aid alongside manual inspection.' },
      { question: 'Can it fix accessibility issues automatically?', answer: 'The checker identifies issues; depending on the result, you may need to edit the document or source file.' },
    ],
  },
}

export function getToolSeo(id, tool) {
  const seo = toolSeo[id] || {
    h1: `${tool.name} Locally - Private Browser-Based PDF Tool`,
    intro: `${tool.description}. PDFOmni keeps the workflow local in your browser so common PDF tasks can be completed without uploading documents to a server.`,
    steps: ['Upload your PDF in the tool interface.', 'Choose the settings that match your document workflow.', 'Download the finished PDF output.'],
    why: defaults.privacyAngle,
    advanced: defaults.advanced,
    useCases: ['Preparing documents for email', 'Cleaning files before sharing', 'Handling private PDFs on your own device'],
    faqs: [defaults.safetyFaq],
  }

  return {
    ...seo,
    positioning: seo.positioning || getCompetitivePositioning(tool),
    notes: seo.notes || categoryNotes[tool.category] || categoryNotes.organize,
    related: relatedTools[id] || [{ href: '/guides', label: 'Read PDF guides' }],
  }
}
